[build]
  base = "/"
  publish = "build/client/"
  command = "npm start"

# ---------------
# Redirects
# ---------------

[[redirects]]
  from = "/favicon.ico"
  to = "/img/favicon/favicon.ico"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://new-project-starter-kit.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/analytics/*"
  to = "https://npsk-ackee.herokuapp.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/404?search=:splat"
  status = 404

[[redirects]]
  from = "https://newprojectstarterkit.netlify.com/*"
  to = "https://newprojectstarterkit.com/:splat"
  force = true

# ---------------
# Headers
# ---------------

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = 'https://newprojectstarterkit.com'
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' https://*.cloudfront.net https://polyfill.io;
      style-src 'self' https://*.cloudfront.net;
      img-src 'self' https://*.cloudfront.net;
      font-src 'self' https://*.cloudfront.net;
      upgrade-insecure-requests;'''
    Feature-Policy = '''
      geolocation 'none';
      midi 'none';
      notifications 'none';
      push 'none';
      sync-xhr 'self';
      microphone 'none';
      camera 'none';
      magnetometer 'none';
      gyroscope 'none';
      speaker 'none';
      vibrate 'none';
      fullscreen 'none';
      payment 'none';'''
    Referrer-Policy = 'strict-origin-when-cross-origin'
    Server = ''
    Strict-Transport-Security = '''
      max-age=63072000;
      includeSubDomains;
      preload;''' # 2 years
    Vary = 'Origin'
    X-Content-Type-Options = 'nosniff'
    X-DNS-Prefetch-Control = 'off'
    X-Download-Options = 'noopen'
    X-Frame-Options = 'DENY'
    X-Robots-Tag = 'noindex, nofollow'
    X-Xss-Protection = '1; mode=block'

[[headers]]
  for = "/404/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/api/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/offline/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"