name: Ping Heroku

on:
  schedule:
  # Run every 20 minutes between 6 AM - Midnight EDT / 5AM - 11PM EST
  - cron: '0,20,40 0-3,10-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ping Heroku
      run: curl -s "${API}"
      env:
        API: ${{ secrets.API_URL }}