name: Ping Heroku

on:
  schedule:
  - cron: '30 6-23 * * *'

jobs:
  build:
    steps:
    - name: Ping Heroku
      runs-on: ubuntu-latest
      run: curl -s -X POST "${URL}"
      env:
        URL: ${{ secrets.API_URL }}
