name: Ping Heroku

on:
  schedule:
  - cron: '30 6-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ping Heroku
      run: curl -s -X POST "${URL}"
      env:
        URL: ${{ secrets.API_URL }}
